#!/usr/bin/env bash

set -e

# Ansi color code variables
red="\033[0;91m"
blue="\033[0;94m"
expand_bg="\033[K"
blue_bg="\033[0;104m${expand_bg}"
red_bg="\033[0;101m${expand_bg}"
green_bg="\033[0;102m${expand_bg}"
green="\033[0;92m"
white="\033[0;97m"
bold="\033[1m"
uline="\033[4m"
reset="\033[0m"

function info {
	echo -e "\n${blue}[install]${reset} $1"
}

function error {
	echo -e "\n${red}[install]${reset} $1"
	exit 1
}

if [ "$#" -ne 1 ]; then
	error "usage: ./install SYSTEM\nsystem can be: linux, macos"
fi

system=$1

info "updating channels"
nix-channel --update

info "updating nix${reset}"
nix flake update

info "building"
nix build .\#$system

info "switch"
./result/sw/bin/darwin-rebuild switch --flake .\#$system
