env:
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-monterey-base:latest
  LINUX_BUILD_IMAGE: nixos/nix:latest
  NIX_INSTALL_URL: https://nixos.org/nix/install
  SUDO: sudo

build_template: &BUILD_TEMPLATE
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_TAG != "" || $CIRRUS_PR != "" || $CIRRUS_BUILD_SOURCE == ""
  name: build_${CIRRUS_OS}_${ARCH}
  timeout_in: 120m
  enable_flake_script: echo "experimental-features = nix-command flakes" | $SUDO tee -a /etc/nix/nix.conf
  install_cachix_script: nix-env -iA cachix -f https://cachix.org/api/v1/install
  flake_check_script: nix flake check -j auto --system ${ARCH//arm/aarch}-{CIRRUS_OS} -v --show-trace

build_darwin_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        ARCH: arm64
    - env:
        ARCH: x86_64
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: bash <(curl -L "$NIX_INSTALL_URL") --daemon
  enable_multi_arch_script: echo "extra-platforms = x86_64-darwin aarch64-darwin" | sudo tee -a /etc/nix/nix.conf
  enable_trusted_users_script: echo "trusted-users = root admin" | sudo tee -a /etc/nix/nix.conf
  kickstart_nix_daemon_script: sudo launchctl kickstart -k system/org.nixos.nix-daemon
  <<: *BUILD_TEMPLATE

build_linux_task:
  matrix:
    - arm_container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 12G
      env:
        ARCH: arm64
    - container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 12G
      env:
        ARCH: x86_64
  env:
    SUDO: ""
  <<: *BUILD_TEMPLATE
