# global env values
env:
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-monterey-base:latest
  LINUX_BUILD_IMAGE: nixos/nix:latest
  SUDO: sudo

build_template: &BUILD_TEMPLATE
  enable_flake_script: echo "experimental-features = nix-command flakes" | $SUDO tee -a /etc/nix/nix.conf
  install_cachix_script: nix-env -iA cachix -f https://cachix.org/api/v1/install
  flake_check_script: nix flake check -v --show-trace

build_darwin_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        ARCH: arm64
    - env:
        ARCH: x86_64
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: arch -$ARCH ./bin/install-nix.sh
  enable_trusted_users_script: echo "trusted-users = root admin" | $SUDO tee -a /etc/nix/nix.conf && sudo launchctl kickstart -k system/org.nixos.nix-daemon
  <<: *BUILD_TEMPLATE

build_linux_task:
  matrix:
    - arm_container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 8G
      env:
        ARCH: arm64
        SUDO: ""
    - container:
        image: $LINUX_BUILD_IMAGE
        cpu: 4
        memory: 8G
      env:
        ARCH: x86_64
  env:
    ARCH: x86_64
    SUDO: ""
  <<: *RUN_BUILD_TEMPLATE
