keys:
  - &users:
    - &stelth F50EE1F161E4AD86DF630B00BA342F8A9C9C2ED0
  - &hosts:
    - &kvasir age14sncf8qh2d9w8txerxda6hdp3865kd5rvu96j9fm498ewhdtnpnq4gk7u8

creation_rules:
  - path_regex: hosts/kvasir/secrets.ya?ml$
    key_groups:
      - age:
          - *kvasir
        pgp:
          - *stelth
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *kvasir
        pgp:
          - *stelth
