# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  modulesPath,
  ...
}: {
  imports = [
    ../common/optional/ephemeral-btrfs.nix
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["ata_generic" "ehci_pci" "ahci" "isci" "xhci_pci" "usbhid" "sd_mod" "sr_mod"];
      kernelModules = ["kvm-intel"];
    };

    loader = {
      grub = {
        enable = true;
        version = 2;
        device = "/dev/sda";
        configurationLimit = 10;
      };
    };
  };

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-label/${config.networking.hostName}-boot";
      fsType = "ext4";
    };
    "/srv/logs" = {
      device = "/dev/disk/by-label/data";
      fsType = "btrfs";
      options = ["subvol=logs" "noatime" "compress=zstd"];
    };
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 8196;
    }
  ];

  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
}
