[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'nord-vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'nord',
		\ }
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
	colorscheme nord
'''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
