[[plugins]]
repo = 'cocopon/iceberg.vim'
name = 'iceberg'
hook_add = '''
  set background=dark
  colorscheme iceberg
'''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
name = 'vim-tmux-navigator'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
name = 'vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
name = 'vim-ft-help_fold'

[[plugins]]
repo = 'kana/vim-textobj-user'
name = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'
name = 'vim-operator-user'

[[plugins]]
repo = 'Shirk/vim-gas'
name = 'vim-gas'

[[plugins]]
repo = 'chrisbra/vim-zsh'
name = 'vim-zsh'

[[plugins]]
repo = 'roxma/nvim-yarp'
name = 'nvim-yarp'
