require("staline").setup({
  sections = {
    left = {
      " ",
      "right_sep_double",
      "-mode",
      "left_sep_double",
      " ",
      "right_sep_double",
      "-file_name",
      "left_sep_double",
      " ",
      "right_sep_double",
      "-branch",
      "left_sep_double",
      " ",
    },
    mid = { "lsp" },
    right = {
      "right_sep_double",
      "- ",
      "-lsp_name",
      "- ",
      "left_sep_double",
      " ",
      "right_sep_double",
      "-line_column",
      "left_sep_double",
      " ",
    },
  },

  defaults = {
    expand_null_ls = true,
    left_separator = "",
    right_separator = "",
    true_colors = true,
    line_column = "[%l:%c] 並%p%% ",
  },
})
