" highlight search
hi search cterm=none ctermfg=white ctermbg=darkyellow
" vertical split color
hi vertsplit guibg=white guifg=white ctermbg=white ctermfg=white

" => Plugin settings

" vim-cmake {{{
" }}}
