---
Diagnostics:
  ClangTidy:
    Add:
      [
        "clang-diagnostic-*",
        "clang-analyzer-*",
        "cppcoreguidelines-*",
        "modernize-*",
        "readability-*",
        "bugprone-*",
      ]
  UnusedIncludes: Strict
