name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 9am UTC, or roughly 3am central
    - cron: "0 9 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    name: Update flake.lock
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "Update flake.lock"
          pr-labels: |
      - name: Merge flake.lock update-flake-lock
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.update.outputs.pull-request-number }}
