name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 9am UTC, or roughly 4am central
    - cron: "0 9 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update flake.lock
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: flakebot
          commit_user_email: flakebot@users.noreply.github.com
          commit_author: Jason Cox <steel300@gmail.com>
          commit_message: "chore(nix): auto update flake.lock"
          push_options: "--force"
