name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 9am UTC, or roughly 3am central
    - cron: "0 0 * * SUN"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update flake.lock
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "Update flake.lock"
          pr-labels: |
      - name: Merge flake.lock update-flake-lock
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        if: ${{ steps.update.outputs.pull-request-number }} != 0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.update.outputs.pull-request-number }}
